### ISSUE TITLE
install-sh is missing

### ISSUE THREAD

**Issue by joriszwart** [DoogeJ/netmonitor-ng#2]
``` sh
$ ./configure
configure: error: cannot find install-sh or install.sh in . ./.. ./../..
```

**Comment by NoxiousPluK** [comment]
Fixed \o/

Thank you!

![643a572e-ae4b-11e5-9eb2-591c95346889](https://cloud.githubusercontent.com/assets/4255780/12074918/fc1db614-b16e-11e5-992b-ee255aca1bec.png)
